version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_files:/var/www/html
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp_files:/var/www/html

volumes:
  wp_files: