version: '3'

services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx-container
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
  wordpress:
    image: wordpress
    build: requirements/wordpress
    container_name: wordpress-container
    depends_on:
      - mariadb
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
  mariadb:
    image: mariadb
    build: requirements/mariadb
    container_name: mariadb-container
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception


volumes:
  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/makacem/data/WordPress'
  DB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/makacem/data/DB'

networks:
  inception:
    driver: bridge