version: '3'

services:
  nginx:
    image: nginx-image
    build: requirements/nginx/
    container_name: nginx-container
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_files:/var/www/html
  wordpress:
    image: wordpress-image
    build: requirements/wordpress
    container_name: wordpress-container
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
  mariadb:
    image: mariadb-image
    build: requirements/mariadb
    container_name: mariadb-container
    env_file:
      - .env



volumes:
  wp_files: