version: '3'

services:
  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
      - "80:80"
    restart: always
  wordpress:
    build: requirements/wordpress
    ports:
      - "9000:9000"
    restart: always
