version: '3'

services:
  nginx:
    image: nginx-image
    build: requirements/nginx/
    container_name: nginx-container
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_files:/var/www/html
  wordpress:
    image: wordpress-image
    build: requirements/wordpress
    container_name: wordpress-container
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_db_password
      WORDPRESS_DB_HOST: mariadb:3306
    volumes:
      - wp_files:/var/www/html
  mariadb:
    image: mariadb-image
    build: requirements/mariadb
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_db_password


volumes:
  wp_files: